export const Prefix = {
  USER_SIGNUP: "USER_SIGNUP",
  USER_LOGIN: "USER_LOGIN",
  USER_LOGOUT: "USER_LOGOUT",
  USER_DATA: "USER_DATA",
  USER_UPDATE_DATA: "USER_UPDATE_DATA"
};

export const Types = {
  //SIGNUP
  USER_SIGNUP_REQUEST: `${Prefix.USER_SIGNUP}_REQUEST`,
  USER_SIGNUP_SUCCESS: `${Prefix.USER_SIGNUP}_SUCCESS`,
  USER_SIGNUP_FAILURE: `${Prefix.USER_SIGNUP}_FAILURE`,
  USER_SIGNUP_REMOVE_ERROR: `${Prefix.USER_SIGNUP}_REMOVE_ERROR`,

  //LOGIN
  USER_LOGIN_REQUEST: `${Prefix.USER_LOGIN}_REQUEST`,
  USER_LOGIN_SUCCESS: `${Prefix.USER_LOGIN}_SUCCESS`,
  USER_LOGIN_FAILURE: `${Prefix.USER_LOGIN}_FAILURE`,
  USER_LOGIN_REMOVE_ERROR: `${Prefix.USER_LOGIN}_REMOVE_ERROR`,

  //LOGOUT
  USER_LOGOUT_REQUEST: `${Prefix.USER_LOGOUT}_REQUEST`,
  USER_LOGOUT_SUCCESS: `${Prefix.USER_LOGOUT}_SUCCESS`,
  USER_LOGOUT_FAILURE: `${Prefix.USER_LOGOUT}_FAILURE`,
  USER_LOGOUT_REMOVE_ERROR: `${Prefix.USER_LOGOUT}_REMOVE_ERROR`,

  //DATA
  USER_DATA_REQUEST: `${Prefix.USER_DATA}_REQUEST`,
  USER_DATA_SUCCESS: `${Prefix.USER_DATA}_SUCCESS`,
  USER_DATA_FAILURE: `${Prefix.USER_DATA}_FAILURE`,
  USER_DATA_REMOVE_ERROR: `${Prefix.USER_DATA}_REMOVE_ERROR`,

  //UPDATE DATA
  USER_UPDATE_DATA_REQUEST: `${Prefix.USER_UPDATE_DATA}_REQUEST`,
  USER_UPDATE_DATA_SUCCESS: `${Prefix.USER_UPDATE_DATA}_SUCCESS`,
  USER_UPDATE_DATA_FAILURE: `${Prefix.USER_UPDATE_DATA}_FAILURE`,
  USER_UPDATE_DATA_REMOVE_ERROR: `${Prefix.USER_UPDATE_DATA}_REMOVE_ERROR`
};

const INITIAL_STATE = {
  nome: null,
  cpf: null,
  telefone: null,
  email: null
};

export default function user(state = INITIAL_STATE, action) {
  const { payload, type } = action;

  switch (type) {
    case Types.USER_DATA_SUCCESS:
    case Types.USER_LOGIN_SUCCESS:
    case Types.USER_UPDATE_DATA_SUCCESS:
      return { ...state, ...payload };

    case Types.USER_LOGOUT_SUCCESS:
      return INITIAL_STATE;

    default:
      return state;
  }
}
